name: ecommerce_cloth
description: E-commerce cloth
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'

# Add packages and plugins
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0
  riverpod: ^2.2.0
  flutter_local_notifications: ^13.0.0
  firebase_storage: ^11.0.14
  firebase_ui_firestore: ^1.2.8
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  flutter_svg: ^2.0.2
  page_transition: ^2.0.9
  auto_route: ^5.0.4
  equatable: ^2.0.5
  flutter_facebook_auth: ^5.0.7
  dio: ^5.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

  # Assets and fonts
flutter:
  uses-material-design: true

  # Add icons, images
  assets:
     - assets/
     - assets/icons/
     - assets/fonts/
     - assets/images/

  # Add fonts
  fonts:
     - family: Metropolis
       fonts:
        - asset: assets/fonts/Metropolis-Black.otf
          weight: 900
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
